//  generated by treegl
    precision highp float;
    attribute vec3 aPosition;
    attribute vec4 aVertexColor;
    attribute vec2 aTexCoord;
    uniform mat4 pmvMatrix;
    varying vec4 color4;
    varying vec2 texCoords2;
    void main() {
      color4 = aVertexColor;
      texCoords2 = aTexCoord;
      gl_Position = pmvMatrix * vec4(aPosition, 1.0);
    }